/**
 * Created by Hugh on 11/5/2018.
 */

export const INIT_QUESTION = "INIT_QUESTION";
export const PERSONAL_INFO = "PERSONAL_INFO";
export const GENERAL_INFORMATION = "GENERAL_INFORMATION";
export const INDIVIDUAL_INFORMATION = "INDIVIDUAL_INFORMATION";
export const ASSETS = "ASSETS";
export const LIABILITIES = "LIABILITIES";
export const INCOME_EXPENDITURES = "INCOME_EXPENDITURES";
export const CONTINGENT_LIABILITES = "CONTINGENT_LIABILITES";
export const MARKETABLE_SECURITIES_SCHEDULE = "MARKETABLE_SECURITIES_SCHEDULE";
export const NON_MARKETABLE_SECURITIES_SCHEDULE =
  "NON_MARKETABLE_SECURITIES_SCHEDULE";
export const REAL_ESTATE_SCHEDULE = "REAL_ESTATE_SCHEDULE";
export const LIFE_INSURANCE_SCHEDULE = "LIFE_INSURANCE_SCHEDULE";
export const CREDIT_OBLIGATIONS_SCHEDULE = "CREDIT_OBLIGATIONS_SCHEDULE";
export const BUSINESS_VENTURES_SCHEDULE = "BUSINESS_VENTURES_SCHEDULE";
export const SIGN_OFF_DISCLAIMER = "SIGN_OFF_DISCLAIMER";
export const CUSTOMER = "CUSTOMER";
export const BANKER = "BANKER";
